apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: haystack-attribution-persistence-email
  namespace: haystack-apps

spec:
  schedule: "30 0 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: attribution-persistence-email
            image: ${image}
            volumeMounts:
            - mountPath: /config
              name: config-volume
            env:
            - name: "HAYSTACK_OVERRIDES_CONFIG_PATH"
              value: "/config/attribution-email.conf"
            - name: "HAYSTACK_GRAPHITE_HOST"
              value: "${graphite_host}"
            - name: "HAYSTACK_GRAPHITE_PORT"
              value: "${graphite_port}"
            - name: "HAYSTACK_GRAPHITE_ENABLED"
              value: "${graphite_enabled}"
            - name: "JAVA_XMS"
              value: "${jvm_memory_limit}m"
            - name: "JAVA_XMX"
              value: "${jvm_memory_limit}m"
            ${env_vars}
          imagePullSecrets:
          - name: regcred
          restartPolicy: OnFailure
          volumes:
          - name: config-volume
            configMap:
              name: ${configmap_name}