/*
 *  Copyright 2020 Expedia Group
 *
 *     Licensed under the Apache License, Version 2.0 (the "License");
 *     you may not use this file except in compliance with the License.
 *     You may obtain a copy of the License at
 *
 *         http://www.apache.org/licenses/LICENSE-2.0
 *
 *     Unless required by applicable law or agreed to in writing, software
 *     distributed under the License is distributed on an "AS IS" BASIS,
 *     WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *     See the License for the specific language governing permissions and
 *     limitations under the License.
 *
 */

package com.expedia.www.haystack.attribution.persistence.s3.config.entities

/**
  * S3 config collection for persisting attributed data
  *
  * @param items collection of s3 configs
  */
case class PersistS3ConfigurationList(items: Seq[PersistS3Configuration])


/**
  * S3 config for persisting attributed data
  *
  * @param enabled       enable/disable this sink
  * @param useStsRole    flag for to enable/disable cross account access
  * @param stsRoleArn    sts role for cross account access
  * @param bucket        s3 bucket name
  * @param folderPath    folder path in s3 bucket
  * @param transformerId id of the transformer config for persisting the report generated by that transformer
  */
case class PersistS3Configuration(enabled: Boolean,
                                  useStsRole: Boolean,
                                  stsRoleArn: String,
                                  bucket: String,
                                  folderPath: String,
                                  transformerId: List[String])